# -*- coding: utf-8 -*-
"""Pet Breeds Image Classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c7W7J_1YSOH6PSawZpqDonqKzRVaFKHI
"""

from google.colab import drive

drive.mount("/content/gdrive")

#importing required libraries
from skimage.io import imread
from skimage.transform import resize
from skimage.feature import hog
from skimage import exposure
import matplotlib.pyplot as plt

# reading the image
img = imread(r'/content/gdrive/MyDrive/animals/cats/cats_00001.jpg')
plt.axis("off")
plt.imshow(img)
print(img.shape)

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
import pandas as pd
from skimage.io import imread
from skimage.transform import resize
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from sklearn.cluster import SpectralClustering
from sklearn.metrics import silhouette_score
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

sample_pet_image = imread(r'/content/gdrive/My Drive/23 Pet Breeds Image Classification/Pet_Breeds/abyssinian/abyssinian_1.jpg', as_gray= True)
plt.imshow(sample_pet_image, cmap=cm.gray)
plt.colorbar()
plt.title('Pet Image Sample')
print(f"the size of the data is {sample_pet_image.shape[0]} pixel hieght and {sample_pet_image.shape[1]} pixel width")
print(f"the minimum pixel value is {sample_pet_image.min()}")
print(f"the maximum pixel value is {sample_pet_image.max()}")
print(f"the mean pixel value is {sample_pet_image.mean()}")
print(f"the standard deviation pixel value is {sample_pet_image.std()}")

plt.show()